name: markdown_to_pdf
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  html: ^0.15.0
  http: ^0.13.5
  markdown: ^6.0.0
  pdf: ^3.8.3